# Generated by Django 4.2.25 on 2025-10-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('bio', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('publish_year', models.IntegerField()),
                ('copy_qunatity', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('ISBN', models.IntegerField(unique=True)),
                ('Author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarys.author')),
            ],
        ),
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('join_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('addrers', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrow_date', models.DateField()),
                ('return_Date', models.DateField()),
                ('fine', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarys.book')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarys.member')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Catergory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarys.catergory'),
        ),
        migrations.AddField(
            model_name='book',
            name='Publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarys.publisher'),
        ),
    ]
