# Generated by Django 4.2.25 on 2025-10-31 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
