# Generated by Django 4.2.25 on 2025-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
