# Generated by Django 4.2.25 on 2025-10-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_enrollment_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
