# Generated by Django 5.2.8 on 2025-11-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shelter.pet'),
        ),
    ]
