# Generated by Django 5.2.8 on 2025-11-06 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelter', '0002_alter_owner_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^([+]?\\d{1,2}[-\\s]?|)\\d{3}[-\\s]?\\d{3}[-\\s]?\\d{4}$')]),
        ),
    ]
